#!/data/data/com.termux/files/usr/bin/bash

clear
echo ""
echo "TERMUX BACKUP"
echo "USAGE:"
echo ""
echo "Backup:"
echo "termux-pkg-backup [FILENAME OF BACKUP FILE TO BE CREATED]"
echo ""
echo "Restore:"
echo "termux-pkg-restore [FILENAME OF BACKUP FILE TO BE RESTORED]"
echo ""
echo "Delete a package list:"
echo "termux-pkg-delete [FILENAME OF BACKUP FILE TO BE DELETED]"
echo ""
echo "Uninstall Termux Backup:"
echo "termux-pkg-uninstall"
echo ""
echo "Perform a full backup:"
echo "full-backup"
echo ""
echo ""
echo ""
echo "Backing up $HOME..."
echo ""
echo "Log:"
echo '-----------------------------------------'
echo ""
echo "Backup started on:"
date
echo ""
mkdir $HOME/0/external-1/termux-backups
echo "command 'full-backup' started..." >> $HOME/0/external-1/termux-backups/log.txt
date >> $HOME/0/external-1/termux-backups/log.txt
tar -cf $HOME/0/external-1/termux-backups/home.tar $HOME
echo ""
echo "command 'full-backup' finished..." >> $HOME/0/external-1/termux-backups/log.txt
date >> $HOME/0/external-1/termux-backups/log.txt
echo ""
echo "command 'termux-pkg-backup' started..." >> $HOME/0/external-1/termux-backups/log.txt
date >> $HOME/0/external-1/termux-backups/log.txt
dpkg --get-selections | cut -f1 > $HOME/0/external-1/termux-backups/termux-packages.txt
echo "command 'termux-pkg-backup' finished..." >> $HOME/0/external-1/termux-backups/log.txt
date >> $HOME/0/external-1/termux-backups/log.txt
echo "-----------------------------------" >> $HOME/0/external-1/termux-backups/log.txt
echo ""
echo "Backing up $HOME... Done!"
echo ""
echo "Backup finished on:"
date
echo ""
exit 0
