#!/data/data/com.termux/files/usr/bin/bash

clear
echo ""
echo "Backing up $HOME..."
echo ""
echo "Log:"
echo '-----------------------------------------'
echo ""
echo "Backup started on:"
date
echo ""
mkdir $HOME/0/external-1/termux-backups
echo "command 'full-backup' started..." >> $HOME/0/external-1/termux-backups/log.txt
date >> $HOME/0/external-1/termux-backups/log.txt
cp -r $HOME $HOME/0/external-1/termux-backups
echo ""
echo "Backup finished on:"
date
echo "command 'full-backup' finished..." >> $HOME/0/external-1/termux-backups/log.txt
date >> $HOME/0/external-1/termux-backups/log.txt
echo "-----------------------------------" >> $HOME/0/external-1/termux-backups/log.txt
echo ""
echo "Backing up $HOME... Done!"
echo ""
exit 0
